### ISSUE TITLE
24 of Octobeer

### ISSUE THREAD

**Issue by AlwxSin** [moscow-python-beer/we-pub#1]
How about organizing a new beer meetup at White Eagles Pub at 24 of October?

**Comment by kxepal** [comment]
Yes, it will. Quite soon we'll announce it. Stay tuned!

**Comment by zzzsochi** [comment]
Дык накидайте объявление же. В нём надо упомянуть про скорую смерть митапкома. Прямо тут обсудим и запилим. Хорошо бы сделать сегодня-завтра, думаю.

P.S. В жопу инглиш!
P.P.S. Если всё пойдёт по плану, то к тому четвергу я уже даже вернусь...  :-)
